-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "desc:Samsung Display Corp. 0x4208", mode = "1920x1200@60.003", position = "0x0", scale = 1, vrr = 1 })
hl.monitor({ output = "desc:Wacom Tech Wacom DTH135 6AH01H1000186", mode = "1920x1080@60.000", position = "0x1200", scale = 1, vrr = 1 })
