# Administration is private over Tailscale.
Host homelab-pve
    HostName 100.84.103.102
    User root
    IdentitiesOnly yes
    IdentityFile ~/.ssh/id_ed25519

Host homelab-services
    HostName 10.77.10.10
    User humunkulud
    ProxyJump homelab-pve

Host homelab-dev
    HostName 10.77.20.10
    User humunkulud
    ProxyJump homelab-pve

Host homelab-ci
    HostName 10.77.30.10
    User humunkulud
    ProxyJump homelab-pve
