# alice-vision package installs the vocabulary tree but omits this in profile.d
ALICEVISION_ROOT=/usr
ALICEVISION_SENSOR_DB=/usr/share/aliceVision/cameraSensors.db
ALICEVISION_VOCTREE=/usr/share/aliceVision/vlfeat_K80L3.SIFT.tree
