-- Hyprland + Dank Material Shell (DMS)
-- Managed in ~/Documents/config — safe alongside Plasma / DWM.
-- Rollback: pick Plasma (or startx/dwm) at login; see docs/hyprland-dms.md

hl.config({ autogenerated = false })

-- Wayland / Qt hints for this session only (does not affect Plasma via environment.d)
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("QT_QPA_PLATFORMTHEME", "gtk3")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")

-- Start DMS from this compositor only (do NOT systemctl --user enable dms —
-- that would also pull DMS into Plasma via graphical-session.target).
hl.on("hyprland.start", function()
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
	hl.exec_cmd("systemctl --user start hyprland-session.target")
	-- Do not start hyprpolkitagent / polkit-kde here: DMS registers its own
	-- Quickshell Polkit agent (themed modal). Only one agent may own the bus.
	hl.exec_cmd("systemctl --user stop hyprpolkitagent.service")
	-- Secret Service + kwallet-pam socket (Plasma uses plasma-kwallet-pam.service)
	hl.exec_cmd("systemctl --user start hypr-kwallet.service")
	-- Dank Material Shell (bar, control center, notifications, lock, polkit, …)
	hl.exec_cmd("dms run -d")
end)

hl.config({
	input = {
		-- German layout (VC/X11 is de); empty would fall back to us
		kb_layout = "de",
		numlock_by_default = true,
		follow_mouse = 1,
		touchpad = {
			tap_to_click = true,
			natural_scroll = true,
		},
	},
	general = {
		gaps_in = 2,
		gaps_out = 2,
		border_size = 2,
		layout = "dwindle",
	},
	decoration = {
		rounding = 4,
		active_opacity = 1.0,
		inactive_opacity = 1.0,
		shadow = {
			enabled = true,
			range = 30,
			render_power = 5,
			offset = "0 5",
			color = "rgba(00000070)",
		},
		blur = {
			enabled = true,
			size = 8,
			passes = 2,
			ignore_opacity = true,
			noise = 0.01,
			vibrancy = 0.15,
			xray = false,
		},
	},
	misc = {
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
	},
	dwindle = {
		preserve_split = true,
	},
	master = {
		mfact = 0.5,
	},
})

hl.animation({ leaf = "windowsIn", enabled = true, speed = 2, bezier = "default" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 2, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 2, bezier = "default" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 2, bezier = "default" })
hl.animation({ leaf = "fade", enabled = true, speed = 1.5, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 1.5, bezier = "default" })

hl.window_rule({ match = { class = "^(org\\.wezfurlong\\.wezterm)$" }, tile = true })
hl.window_rule({
	name = "zen-frosted-glass",
	match = { class = "^(zen)$" },
	opacity = "0.94 0.90",
})
hl.window_rule({ match = { class = "^(pavucontrol)$" }, tile = true })
hl.window_rule({ match = { class = "^(nm-connection-editor)$" }, tile = true })
hl.window_rule({ match = { class = "^(blueman-manager)$" }, float = true })
hl.window_rule({ match = { class = "^(xdg-desktop-portal)$" }, float = true })
hl.window_rule({
	match = { class = "^(steam)$", title = "^(notificationtoasts)" },
	no_initial_focus = true,
	pin = true,
})
hl.window_rule({
	match = { class = "^(firefox)$", title = "^(Picture-in-Picture)$" },
	float = true,
})
hl.window_rule({
	match = { class = "^(zen)$", title = "^(Picture-in-Picture)$" },
	float = true,
})
hl.window_rule({ match = { class = "^(zoom)$" }, float = true })
hl.layer_rule({ match = { namespace = "^(quickshell)$" }, no_anim = true })
hl.layer_rule({ match = { namespace = "^dms:.*" }, no_anim = true })

-- DMS-managed fragments (Settings UI writes some of these)
require("dms.colors")
require("dms.outputs")
require("dms.wacom") -- Movink pen/touch → Movink panel (survives DP-N renames)
require("dms.layout")

require("dms.layout-user") -- gaps/rounding prefs (survives DMS rewriting layout.lua)
require("dms.cursor")
require("dms.binds")
require("dms.binds-user")
require("dms.workspaces") -- DWM-style per-monitor tags (hyprsplit); after binds
require("dms.windowrules")

-- Laptop lid: only the internal display sleeps; logind is inhibited by laptop-lid-awake.service.
hl.bind("switch:on:Lid Switch", hl.dsp.dpms({ action = "off", monitor = "eDP-1" }), { locked = true })
hl.bind("switch:off:Lid Switch", hl.dsp.dpms({ action = "on", monitor = "eDP-1" }), { locked = true })
